### ISSUE TITLE
How Combo breaker work?

### ISSUE THREAD

**Issue by pc223** [samyk/combobreaker#1]
Your project is so Awesomeeeeee!! :smile: 
But i want to know how it work, i don't think it Brute force with only 30s :smile:

**Comment by samyk** [comment]
These videos explain the reduction attack:
https://www.youtube.com/watch?v=09UgmwtL12c (online tool)
https://www.youtube.com/watch?v=qkolWO6pAL8 (actual vuln)

**Comment by Scott216** [comment]
I just finished watching your videos.  You are the combo-lock whisperer :)

**Comment by geek213** [comment]
building the advanced combo breaker - having the parts printed for me.
do i just need the combo-breaker-chassis code? (does that code it include  a dial-gripper?)
- or do i need to send the stepper-long-gripper code too?
  thx

**Comment by samyk** [comment]
You need to print a gripper that works for the stepper motor you chose (look at the length of the arm and whether the shaft shape is a D or O). You may need to adjust for tolerances in your print as well.

**Comment by geek213** [comment]
the shaft is an "O"; diameter is ,195" and the length is .717".
would i print the stepper-long-gripper and cut to length?

**Comment by chefterry76** [comment]
where is the code for the basic version tnx
