### ISSUE TITLE
Where is the encoder.h file that is <included> in the combobreaker.ino sketch file?

### ISSUE THREAD

**Issue by cnewlander** [samyk/combobreaker#10]
The combobreaker.ino will not compile with either arduino 1.6.13 or 1.8 because the header file encoder.h is missing.   Where can this file be sourced?   Or what needs to be configured to get this sketch to compile?

**Comment by AidanMcCarthy** [comment]
Try here:
https://www.pjrc.com/teensy/td_libs_Encoder.html

Not sure if this is the same one that @samyk used?

**Comment by cnewlander** [comment]
Thanks, but if you aren't sure your suggestion is not helpful and only adds confusion.   :)

**Comment by samyk** [comment]
@teamstarlet is correct

**Comment by cnewlander** [comment]
Thanks @teamstarlet , @samylk 

The above library is included with Arduino 1.6.13  To install it:

Arduion IDE -> Sketch -> Include Library -> Manage Libraries -> enter "encoder" in the "filter your search..." textbox.  Then select the Encoder by Paul Stoffregen then select the install button.  

 installed version 1.4.1 and the code compiles.

**Comment by sl33p3rc3ll** [comment]
Thanks to all!
