### ISSUE TITLE
L7805 5V Regulator Connection Concern

### ISSUE THREAD

**Issue by adamaero** [samyk/combobreaker#12]
The datasheet for the L7805 says that Pin 2 is ground--then why is it connected to the +5V of the power? 
(Smoke started fuming, and wires burned when prototyped on the breadboard.)
After switching to a power supply (not a battery), the overload feature kicked in since it was drawing more than an amp! I'll start from scratch and re-wire, but I just want to understand why Pin 2 is not grounded.

https://www.sparkfun.com/datasheets/Components/LM7805.pdf

**Comment by AidanMcCarthy** [comment]
This has already been corrected. Check out the board that I designed in my
form of the project.

**Comment by adamaero** [comment]
I will look at your schematic, thanks. Although the Eagle layout (not schematic) is the same for the L7805:
**https://github.com/teamstarlet/combobreaker/blob/master/Eagle%20Files/ComboBreaker_top.png**
same connections as
https://github.com/samyk/combobreaker/blob/master/Eagle%20Files/ComboBreaker_top.png

**Comment by AidanMcCarthy** [comment]
https://github.com/teamstarlet/combobreaker/tree/master/PCB

There is the corrected original PCB in there, as well as a much improved (but still needing some work) v2 Eagle PCB that uses a much more efficient OKI78SR for the 5V conversion.

***There's an issue with the grounding of the input power connector which needs to be fixed so I wouldn't send this directly off to be printed unless you want to solder some extra wires!***

![image](https://user-images.githubusercontent.com/25337485/30561560-6fec35a0-9c89-11e7-86c1-f3eb216e07bb.png)
![image](https://user-images.githubusercontent.com/25337485/30561574-790e24f4-9c89-11e7-94aa-2661fb9c5188.png)

**Comment by AidanMcCarthy** [comment]
@samyk This issue can be closed now!

**Comment by samyk** [comment]
Thanks @AidanMcCarthy!

**Comment by adamaero** [comment]
(I think I just powered the Arduino incorrectly by using an external power supply and the Arduino's USB.)
